// CATEGORIES_TYPES
export default {
  ENGINE: 'Двигатель',
  CHASSIS_SERVICE: 'ТО ходовая',
  GAS_SERVICE: 'ТО газ',
  REFUELING: 'Заправка',
  FUEL_SYSTEM: 'Топливная система',
  BRAKE_SYSTEM: 'Тормозная система',
  STEERING: 'Рулевое управление',
  ELECTRONICS: 'Электроника',
  LIGHTS: 'Свет',
  IGNITION_SYSTEM: 'Система зажигания',
  INTAKE_AND_EXHAUST_SYSTEM: 'Система впуска и выпуска',
  COOLING_SYSTEM: 'Система охлаждения',
  HEATING_AND_AIR_CONDITIONING: 'Отопление и кондиционирование',
  CLUTCH: 'Сцепление',
  TRANSMISSIONS: 'Трансмиссии',
  INSURANCE: 'Страховка',
  BODY: 'Кузов',
  INTERIOR: 'Салон',
}
